name: Build mpc-qt

on:
  workflow_dispatch:
    inputs:
      libmpv_url:
        description: 'input libmpv(mpv-dev-x86_64-*.7z) download url'
        default: 'https://github.com/zhongfly/mpv-winbuild/releases/download/2022-07-14/mpv-dev-x86_64-20220714-git-0044c19.7z'
        required: true
      yt-dlp_url:
        description: 'input yt-dlp.exe download url'
        default: 'https://github.com/yt-dlp/yt-dlp/releases/download/2022.06.29/yt-dlp.exe'
        required: true

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v3
        with:
          repository: mpc-qt/mpc-qt
          fetch-depth: 1 
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            base-devel
            wget
            p7zip
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-qt5
            mingw-w64-x86_64-qt-creator
            mingw-w64-x86_64-imagemagick
            mingw-w64-x86_64-librsvg
            mingw-w64-x86_64-inkscape
      - name: Download libmpv
        run: |
          wget -nv -O libmpv.7z ${{ github.event.inputs.libmpv_url }}
          7z x -y libmpv.7z -olibmpv
          cp -f libmpv/* mpv-dev/lib || true
          cp -f libmpv/include/* mpv-dev/include/mpv || true
          wget -nv -O binaries/yt-dlp.exe ${{ github.event.inputs.yt-dlp_url }}
      - name: Build
        run: |
          chmod +x *.sh
          set +e
          bash make-win-icon.sh
          bash make-release-win.sh
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: "mpc-qt-win"
          path: mpc-qt-*.zip
